services:
  workout-tracker:
    image: ghcr.io/jovandeginste/workout-tracker:master
    container_name: wt-app
    restart: unless-stopped
    ports:
      # Host Port:Container Port
      - 8080:8080
    volumes:
      # Mount local directory for sqlite database
      - ./data:/data
    environment:
      - WT_JWT_ENCRYPTION_KEY=my-secret-key
